{"uuid": "5125c63a-8349-4802-8a48-a2d8761a17f7", "children": ["53083d23-00d4-43ce-b6e6-ce9e7a982f56"], "befores": [{"name": "driver", "status": "passed", "start": 1703181335619, "stop": 1703181336878}], "afters": [{"name": "driver::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: You clicked a button\nMessage: unexpected alert open: {Alert text : You clicked a button}\n  (Session info: chrome=120.0.6099.129)\nStacktrace:\n\tGetHandleVerifier [0x00007FF614D92142+3514994]\n\t(No symbol) [0x00007FF6149B0CE2]\n\t(No symbol) [0x00007FF6148576AA]\n\t(No symbol) [0x00007FF6148E2CCC]\n\t(No symbol) [0x00007FF6148C5D93]\n\t(No symbol) [0x00007FF614894BDC]\n\t(No symbol) [0x00007FF614895C64]\n\tGetHandleVerifier [0x00007FF614DBE16B+3695259]\n\tGetHandleVerifier [0x00007FF614E16737+4057191]\n\tGetHandleVerifier [0x00007FF614E0E4E3+4023827]\n\tGetHandleVerifier [0x00007FF614AE04F9+689705]\n\t(No symbol) [0x00007FF6149BC048]\n\t(No symbol) [0x00007FF6149B8044]\n\t(No symbol) [0x00007FF6149B81C9]\n\t(No symbol) [0x00007FF6149A88C4]\n\tBaseThreadInitThunk [0x00007FFD79717344+20]\n\tRtlUserThreadStart [0x00007FFD7B2E26B1+33]\n\n", "trace": "  File \"C:\\PythonProjects\\WebAutomationFramework\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\PythonProjects\\WebAutomationFramework\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 911, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\PythonProjects\\WebAutomationFramework\\conftest.py\", line 13, in driver\n    attach = driver.get_screenshot_as_png()\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\PythonProjects\\WebAutomationFramework\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 838, in get_screenshot_as_png\n    return b64decode(self.get_screenshot_as_base64().encode(\"ascii\"))\n                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\PythonProjects\\WebAutomationFramework\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 849, in get_screenshot_as_base64\n    return self.execute(Command.SCREENSHOT)[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\PythonProjects\\WebAutomationFramework\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\PythonProjects\\WebAutomationFramework\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 228, in check_response\n    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here\n    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1703181339871, "stop": 1703181339876}], "start": 1703181335619, "stop": 1703181339876}